name: Photography by Nature
favicon: null
layout_spectrum: 1
typography_spectrum: 0.13046
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.7608533428616859
  lightness: 0.5625
  saturation: 0.5568461101446953
  rhythmicContrast: 1
purpose: []
