typography_spectrum: 0.13046
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.7608533428616859
  lightness: 0.5625
  saturation: 0.5568461101446953
  rhythmicContrast: 1
opengraph:
  image: null
  type: page
  appId: 'https://www.facebook.com/jeffsphotos/'
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Jeff Niles
  email: jnmusicman9@gmail.com
name: Photography by Nature
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: '"Two soul''s journey through life"'
purpose: []
